name: 'Build'
on:
  push:
      branches:    
        - main
jobs:
  deploy:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: kvrhdn/gha-buildevents@main
        name: gha
        with:
          # Required: Honeycomb API key - needed to send traces.
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}

          # Required: the Honeycomb dataset to use.
          dataset: gha-buildevents_integration

          # Required: the job status, this will be used in the post section and sent
          # as status of the trace. Must always be ${{ job.status }}.
          job-status: ${{ job.status }}
      - uses: actions/checkout@v2
        name: checkout
      - uses: actions/setup-go@v2
        name: go-build
        with:
          go-version: '^1.15.1' # The Go version to download (if necessary) and use.
      - run: go build -o hello .
